[tool.poetry]
name = "wiki-parser"
version = "0.1.0"
description = ""
authors = ["Vladimir Margaryan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
